<?xml version="1.0"?>

<!--
Author: Marcel Stuettgen
email: stuettgen@fh-aachen.de

kinect rgbd camera

-->

<robot>

   <joint name="kinect_base_joint" type="fixed">
    <origin xyz="${-chassis_length/2 + kinect_x_size } 0 ${kinect_mtplate_z_offset - kinect_z_size/2}" rpy="0 ${kinect_pitch} 0" /> <!-- position here -->
    <parent link="mountplate" />
    <child link="camera_link" />
  </joint>


<link name="camera_link">
    <inertial>
      <mass value="0.01" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
        iyy="0.001" iyz="0.0"
        izz="0.001" />
    </inertial>
    <visual>
      <origin xyz=" 0 0 0 " rpy="0 0 0" />
      <geometry>
	<mesh filename="file://$(find rover_description)/meshes/sensors/kinect.dae" scale="0.8 0.8 0.8"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="${-1*(kinect_x_size/2)} 0.0 0.0" rpy="0 0 0" />
      <geometry>
        <box size="${kinect_x_size} ${kinect_y_size} ${kinect_z_size}"/>
      </geometry>
    </collision>
  </link>


  <joint name="kinect_depth_joint" type="fixed">
    <origin xyz="0 0.018 0" rpy="0 0 0" />
    <parent link="camera_link" />
    <child link="kinect_depth_frame" />
  </joint>

  <link name="kinect_depth_frame">
    <inertial>
      <mass value="0.01" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
        iyy="0.001" iyz="0.0"
        izz="0.001" />
    </inertial>
  </link>

  <joint name="kinect_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-PI/2} 0 ${-PI/2}" />
    <parent link="kinect_depth_frame" />
    <child link="kinect_depth_optical_frame" />
  </joint>

  <link name="kinect_depth_optical_frame">
    <inertial>
      <mass value="0.001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
        iyy="0.0001" iyz="0.0"
        izz="0.0001" />
    </inertial>
  </link>

  <joint name="kinect_rgb_joint" type="fixed">
    <origin xyz="0 -0.005 0" rpy="0 0 0" />
    <parent link="camera_link" />
    <child link="kinect_rgb_frame" />
  </joint>

  <link name="kinect_rgb_frame">
    <inertial>
      <mass value="0.001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
        iyy="0.0001" iyz="0.0"
        izz="0.0001" />
    </inertial>
  </link>

  <joint name="kinect_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-PI/2} 0 ${-PI/2}" />
    <parent link="kinect_rgb_frame" />
    <child link="kinect_rgb_optical_frame" />
  </joint>

  <link name="kinect_rgb_optical_frame">
    <inertial>
      <mass value="0.001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
        iyy="0.0001" iyz="0.0"
        izz="0.0001" />
    </inertial>
  </link>

	<!-- SENSOR -->
	<gazebo reference="camera_link">
		<sensor type="depth" name="kinect_rgb_camera">
			<always_on>1</always_on>
			<update_rate>20</update_rate>
        		<visualize>true</visualize>
			<camera>
				<horizontal_fov>1.047</horizontal_fov>
				<image>
					<width>640</width>
					<height>480</height>
					<format>R8G8B8</format>
				</image>
				<clip>
					<near>0.1</near>
					<far>100</far>
				</clip>
			</camera>
			<plugin name="camera_controller" filename="libgazebo_ros_openni_kinect.so">
				<alwaysOn>true</alwaysOn>
        			<updateRate>10.0</updateRate>
	       			<cameraName>camera</cameraName>
        			<frameName>kinect_rgb_optical_frame</frameName>
				<imageTopicName>image_raw</imageTopicName>
				<depthImageTopicName>depth/image_raw</depthImageTopicName>
				<pointCloudTopicName>depth/points</pointCloudTopicName>
				<cameraInfoTopicName>camera_info</cameraInfoTopicName>
				<depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>
				<pointCloudCutoff>0.4</pointCloudCutoff>
        			<hackBaseline>0.07</hackBaseline>
        			<distortionK1>0.0</distortionK1>
        			<distortionK2>0.0</distortionK2>
        			<distortionK3>0.0</distortionK3>
        			<distortionT1>0.0</distortionT1>
        			<distortionT2>0.0</distortionT2>
				<CxPrime>0.0</CxPrime>
				<Cx>0.0</Cx>
				<Cy>0.0</Cy>
				<focalLength>0.0</focalLength>
      			</plugin>
		</sensor>
	</gazebo>


</robot>
