<?xml version="1.0"?>

<!--
Author: Marcel Stuettgen
email: stuettgen@fh-aachen.de

SICK_laser laser scan for the husky

-->


<robot>
	<!-- SICK_laser LINK -->
	<link name="laser_link">
		<inertial>
        		<mass value="0.01" />
			<origin xyz="0 0 0" />
			<inertia ixx="0.01" ixy="0.0" ixz="0.0"
                        	 iyy="0.01" iyz="0.0"
				 izz="0.01" />
		</inertial>

        	<visual>
			<origin xyz="0 0 ${-SICK_laser_z_size/2}" rpy="0 0 0" />
			<geometry>
				<mesh filename="package://rover_description/meshes/sensors/hokuyo.dae"/>
				<!--box size = "0.1 0.1 0.1"/-->
            		</geometry>
        	</visual>

		<collision>
			<geometry>
				<box size="${SICK_laser_x_size} ${SICK_laser_y_size} ${SICK_laser_z_size}" />
				<!--box size = "0.1 0.1 0.1"/-->
			</geometry>
		</collision>
        </link>


	<!-- SICK_laser JOINT -->
	<joint name="SICK_laser_joint" type="fixed">
		<!-- origin xyz="0.23 0 0.29" rpy="0 0 0" /-->
		<origin xyz="${chassis_length/2 + SICK_laser_x_size/2} 0 ${SICK_laser_z_size/2}" rpy="0 0 0" />
        	<parent link="mountplate"/>
        	<child link="laser_link" />
	</joint>


	<!-- SENSOR -->
	<gazebo reference="laser_link">
		<material>Gazebo/Grey</material>
		<sensor name="SICK_laser" type="ray">
			<update_rate>200</update_rate>
			<always_on>1</always_on>
        		<visualize>false</visualize>
        		<ray>
				<scan>
					<horizontal>
              					<samples>820</samples>
              					<resolution>0.5</resolution>
              					<min_angle>${-3.0/4.0 * PI}</min_angle>
              					<max_angle>${ 3.0/4.0 * PI}</max_angle>
            				</horizontal>
          			</scan>
          			<range>
            				<min>0.05</min>
            				<max>25</max>
            				<resolution>0.01</resolution>
         			</range>
       			</ray>
			<plugin name='SICK_laser_plugin' filename='libgazebo_ros_laser.so'>
				<updateRate>200.0</updateRate>
				<frameName>laser_link</frameName>
				<topicName>scan</topicName>
				<gaussianNoise>0.0</gaussianNoise>
				<SICK_laserMinIntensity>101</SICK_laserMinIntensity>
			</plugin>
      		</sensor>
	</gazebo>

</robot>
